image: java:latest

pages:
  stage: deploy
  script: /usr/lib/jvm/java-8-openjdk-amd64/bin/javadoc -sourcepath src -d public -subpackages . -private
  artifacts:
    paths:
    - public
  only:
  - master
