# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: java:latest

pages:
  stage: deploy
  script:
  - ls /usr/lib/jvm
  - mkdir .public
  - /usr/lib/jvm/java-8-openjdk-amd64/bin/javadoc -sourcepath src -d public -subpackages .
  artifacts:
    paths:
    - public
  only:
  - master
